In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
b=np.array([[1,2,3,4],[4,5,6,7]])
print(b)

[[1 2 3 4]
 [4 5 6 7]]


In [5]:
b.ndim

2

In [6]:
a[0]

1

In [8]:
b[1][1]

5

In [9]:
b.itemsize

4

In [11]:
b.dtype

dtype('int32')

In [19]:
c=np.array([1,2,3,4],dtype=complex)
c.dtype
c.itemsize

16

In [20]:
c

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [17]:
b.size

8

In [18]:
b.shape

(2, 4)

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [28]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [31]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a.min()

1

In [38]:
a.max()

6

In [40]:
a.sum()

21

In [41]:
a.sum(axis=0)

array([5, 7, 9])

In [42]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [43]:
np.std(a)

1.707825127659933

In [44]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[1,5,9]])
            

In [45]:
a+b

array([[ 8, 10, 12],
       [ 5, 10, 15]])

In [46]:
a*b

array([[ 7, 16, 27],
       [ 4, 25, 54]])

In [47]:
a/b

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 1.        , 0.66666667]])

In [49]:
a.dot(b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)